package logic;
/*
 * CarOwner class with Hibernate annotations to fill the MySQL table
 * ownerId and ownerName are unique fields
 * ownerId, ownerName can't be null
 * equals() only checks ownerId and ownerName: other fields can be equal
 * one owner may have several cars (oneToMany relations)
 */
import util.ErrorDialog;
import java.util.List;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.persistence.Table;
import javax.persistence.Entity;
import javax.persistence.Column;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.CascadeType;
import javax.persistence.FetchType;

@Table(name = "owners")
@Entity(name = "CarOwner")
public class CarOwner{
	////FIELDS////
	@Id
	@Column(name = "owner_id")
	private int ownerId;
	@Column(name = "owner_name")
	//max 200: russian, english upper and lower letters
	private String ownerName; 
	@Column(name = "owner_tel")
	//possible codes: +375 17/29/33/44/25
	private String ownerTel;
	@OneToMany(cascade = CascadeType.ALL, orphanRemoval = true, fetch = FetchType.EAGER, mappedBy = "owner")
	private List<Car> cars = new ArrayList<>();
	////AUTOGENERATED FUNCTIONS TO GENERATE THE HASHCODE AND TO CHECK FOR EQUALITY////
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ownerId;
		return result;
	}
	@Override
	public boolean equals(Object obj) {
		if (this == obj) return true;
		if (obj == null) return false;
		if (getClass() != obj.getClass()) return false;
		CarOwner other = (CarOwner) obj;
		if (ownerId != other.ownerId) return false;
		if(ownerName == null) {
			if(other.ownerName != null) return false;
		}else if(!ownerName.equals(other.ownerName)) {return false;}
		return true;
	}
	////SETTERS AND GETTERS////
	public void setOwnerId(int ownerId, JFrame frame){
		if(ownerId <= 0){
			ErrorDialog.showErrorDialog(frame, "Неправильный индекс владельца");
		}else{
			this.ownerId = ownerId;
		}	
	}
	public int getOwnerId(){ return ownerId; }
	
	public void setOwnerName(String ownerName, JFrame frame){
		if(ownerName == null) {
			ErrorDialog.showErrorDialog(frame, "Неправильное имя владельца");
		}else {
			this.ownerName = ownerName;
		}
	}
	public String getOwnerName(){ return ownerName; }
	
	public void setCars(List <Car> cars){ this.cars = cars;	}
	public List <Car> getCars(){ return cars; }
	
	public void setOwnerTel(String ownerTel) { this.ownerTel = ownerTel; }
	public String getOwnerTel() { return ownerTel; }
}